home/urls.py
from django.urls import re_path
from .import views

app_name = 'home'

urlpatterns = [
	re_path(r'^$', views.home, name='home')
]

properties/urls.py
from django.urls import re_path
from .import views

app_name = 'properties'

urlpatterns = [
	re_path(r'^$', views.properties, name='properties-list'),
	re_path(r'^properties-create/$', views.property_create, name='properties-create'),
	re_path(r'^property/(?P<slug>[\w-]+)/$', views.property_detail, name='properties-detail'),
	re_path(r'^appartment-create/$', views.appartment_create, name='appartment-create'),
	re_path(r'^house-create/$', views.house_create, name='house-create'),
	re_path(r'^generate-invoice/(?P<slug>[\w-]+)/$', views.generate_invoice, name='generate-invoice'),
]

home/views.py
from django.shortcuts import render
from properties.models import Property

def home(request):
	template_name = 'home/home.html'
	properties = Property.objects.all()

	context = {
		'properties': properties,
	}
	
	return render(request, template_name, context)

home/templates/home/sections/agencies.html
{% load static %}

<section class="ftco-section ftco-agent" id="agencies">
	<div class="container">
		<div class="row justify-content-center pb-5">
			<div class="col-md-12 heading-section text-center ftco-animate">
				<span class="subheading">Agencies</span>
				<h2 class="mb-4">Real Estate Agencies</h2>
			</div>
		</div>
		<div class="row">
			<div class="col-md-3 ftco-animate">
				<div class="agent">
					<div class="img">
						<img src="{% static 'home/images/realestate.jpg' %}" class="img-fluid" alt="">
					</div>
					<div class="desc">
						<h3><a href="properties.html">Green Real Estate</a></h3>
						<p class="h-info"><span class="ion-ios-home icon"></span> <span class="details">43 Properties</span></p>
					</div>
				</div>
			</div>
			<div class="col-md-3 ftco-animate">
				<div class="agent">
					<div class="img">
						<img src="{% static 'home/images/realestate.jpg' %}" class="img-fluid hue-90" alt="">
					</div>
					<div class="desc">
						<h3><a href="properties.html">Blue Real Estate</a></h3>
						<p class="h-info"><span class="ion-ios-home icon"></span> <span class="details">28 Properties</span></p>
					</div>
				</div>
			</div>
			<div class="col-md-3 ftco-animate">
				<div class="agent">
					<div class="img">
						<img src="{% static 'home/images/realestate.jpg' %}" class="img-fluid hue-180" alt="">
					</div>
					<div class="desc">
						<h3><a href="properties.html">Purple Real Estate</a></h3>
						<p class="h-info"><span class="ion-ios-home icon"></span> <span class="details">30 Properties</span></p>
					</div>
				</div>
			</div>
			<div class="col-md-3 ftco-animate">
				<div class="agent">
					<div class="img">
						<img src="{% static 'home/images/realestate.jpg' %}" class="img-fluid grayscale" alt="">
					</div>
					<div class="desc">
						<h3><a href="properties.html">Grey Real Estate</a></h3>
						<p class="h-info"><span class="ion-ios-home icon"></span> <span class="details">25 Properties</span></p>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

home/templates/home/sections/footer.html
<footer class="ftco-footer ftco-section">
		<div class="container">
			<div class="row mb-5">
				<div class="col-md">
					<div class="ftco-footer-widget mb-4">
						<h2 class="ftco-heading-2">RentAll</h2>
						
						<ul class="ftco-footer-social list-unstyled mt-5">
							<li class="ftco-animate"><a href="#"><span class="icon-twitter"></span></a></li>
							<li class="ftco-animate"><a href="#"><span class="icon-facebook"></span></a></li>
							<li class="ftco-animate"><a href="#"><span class="icon-instagram"></span></a></li>
						</ul>
					</div>
				</div>
				<div class="col-md">
					<div class="ftco-footer-widget mb-4 ml-md-4">
						<h2 class="ftco-heading-2">Services</h2>
						<ul class="list-unstyled">
							<li><a href="#"><span class="icon-long-arrow-right mr-2"></span>Search Properties</a></li>
							<li><a href="#"><span class="icon-long-arrow-right mr-2"></span>Support</a></li>
							<li><a href="#"><span class="icon-long-arrow-right mr-2"></span>FAQs</a></li>
						</ul>
					</div>
				</div>
				<div class="col-md">
					<div class="ftco-footer-widget mb-4 ml-md-4">
						<h2 class="ftco-heading-2">About Us</h2>
						<ul class="list-unstyled">
							<li><a href="#"><span class="icon-long-arrow-right mr-2"></span>Our Brand</a></li>
							<li><a href="#"><span class="icon-long-arrow-right mr-2"></span>Registered Agencies</a></li>
						</ul>
					</div>
				</div>

				<div class="col-md">
					<div class="ftco-footer-widget mb-4">
						<h2 class="ftco-heading-2">Get in Touch!</h2>
						<div class="block-23 mb-3">
							<ul>
								<li><a href="#"><span class="icon icon-phone"></span><span class="text">+254 721 822 406</span></a></li>
								<li><a href="#"><span class="icon icon-envelope pr-4"></span><span class="text">laxithirani@gmail.com</span></a></li>
							</ul>
						</div>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-md-12 text-center">

					<p>
						Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved </p>
					</div>
				</div>
			</div>
		</footer>

home/templates/home/sections/landing_page.html
{% load static %}

<div class="" style="background-image: url('{% static 'home/images/couch.jpg' %}');" data-stellar-background-ratio="0.5">
	<div class="overlay"></div>
	<div class="container">
		<div class="row no-gutters slider-text justify-content-center align-items-center pb-10">
			<div class="col-lg-8 col-md-6 ftco-animate d-flex align-items-end">
				<div class="text text-center w-100">
					<h1 class="mb-4">Find A House<br>That Will Make You Happy</h1>
					<p><a href="{% url 'properties:properties-list' %}" class="btn btn-primary py-3 px-4">Search Properties</a></p>
				</div>
			</div>
		</div>
	</div>
</div>

home/templates/home/sections/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
	<div class="container">
		<a class="navbar-brand" href="{% url 'home:home' %}">Al<span class="brown-text">Quiler</span></a>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
			<span class="oi oi-menu"></span> Menu
		</button>

		<div class="collapse navbar-collapse" id="ftco-nav">
			<ul class="navbar-nav ml-auto">
				<li class="nav-item"><a href="{% url 'properties:properties-list' %}" class="nav-link">Properties</a></li>
				<li class="nav-item"><a href="#services" class="nav-link">Services</a></li>
				<li class="nav-item"><a href="#agencies" class="nav-link">Agencies</a></li>
				<li class="nav-item"><a href="#" class="nav-link">Contact</a></li>

				<li class="nav-item">
					<a href="{%url 'account_login' %}" class="nav-link">
					{% if user.is_authenticated %}
						Admin Dashboard
					{% else %}
						Login
					{% endif %}
					</a>
				</li>

			</ul>
		</div>
	</div>
</nav>

home/templates/home/sections/properties.html
{% load static %}

<section class="ftco-section goto-here" id="properties">
	<div class="container">
		<div class="row justify-content-center">
			<div class="col-md-12 heading-section text-center ftco-animate mb-5">
				<span class="subheading">What we offer</span>
				<h2 class="mb-2">Some Of Our Properties</h2>
			</div>
		</div>
		<div class="row">
			{% for property in properties %}
				<div class="col-md-4">
					<div class="property-wrap">
						<div class="img d-flex align-items-center justify-content-center" style="background-image: url(' {% if property.image %} {{ property.image.url }} {% else %} {% static 'home/images/work-1.jpg' %} {% endif %}');"> 
							<a href="#"></a>
							<div class="list-agent d-flex align-items-center">
								<a href="#" class="agent-info d-flex align-items-center">
									<h3 class="mb-0 ml-2">{{ property.name }}</h3>
								</a>
								<div class="tooltip-wrap d-flex"> 
									<a href="#" class="icon-2 d-flex align-items-center justify-content-center" data-toggle="tooltip" data-placement="top" title="Like">
										<span class="ion-ios-heart"><i class="sr-only">Like</i></span>
									</a>
									<a href="#" class="icon-2 d-flex align-items-center justify-content-center" data-toggle="tooltip" data-placement="top" title="View">
										<span class="ion-ios-eye"><i class="sr-only">View</i></span>
									</a>
								</div>
							</div>
						</div>
						<div class="text">
							<p class="price mb-3"><span class="orig-price">{{ property.rent }}<small>/month</small></span></p>
							<h3 class="mb-0"><a href="#">{{property.name}}</a></h3>
							<span class="location d-inline-block mb-3"><i class="ion-ios-pin mr-2"></i>{{ property.address }}</span>
							<ul class="property_list">
								<li><span class="flaticon-bed"></span>{{ property.bedrooms }}</li>
								<li><span class="flaticon-bathtub"></span>{{ property.washrooms }}</li>
							</ul>
						</div>
					</div>
				</div>
			{% empty %}
				<p class="text-center w-100">Properties don't exist yet!</p>
			{% endfor %}

		</div>
		</div>
	</div>
</section>

home/templates/home/sections/services.html
{% load static %}

<section class="ftco-section ftco-fullwidth" id="services">
	<div class="overlay"></div>
	<div class="container">
		<div class="row justify-content-center">
			<div class="col-md-12 heading-section text-center ftco-animate mb-5">
				<span class="subheading">Services</span>
				<h2 class="mb-2">Why Choose Us?</h2>
			</div>
		</div>
	</div>
	<div class="container-fluid px-0">
		<div class="row d-md-flex text-wrapper align-items-stretch">
			<div class="one-half mb-md-0 mb-4 img d-flex align-self-stretch"></div>
			<div class="one-half half-text d-flex justify-content-center align-items-center">
				<div class="text-inner pl-md-5">
					<div class="row d-flex">
						<div class="col-md-12 d-flex align-self-stretch ftco-animate">
							<div class="media block-6 services-wrap d-flex">
								<div class="icon d-flex justify-content-center align-items-center"><span class="flaticon-piggy-bank"></span></div>
								<div class="media-body pl-4">
									<h3>Easy Search</h3>
									<p>Searching for houses couldn't be made any easier for tenants</p>
								</div>
							</div>      
						</div>
						<div class="col-md-12 d-flex align-self-stretch ftco-animate">
							<div class="media block-6 services-wrap d-flex">
								<div class="icon d-flex justify-content-center align-items-center"><span class="flaticon-wallet"></span></div>
								<div class="media-body pl-4">
									<h3>Reports</h3>
									<p> Landlord to generate monthly invoices and generate reports for their payment</p>
								</div>
							</div>      
						</div>
						<div class="col-md-12 d-flex align-self-stretch ftco-animate">
							<div class="media block-6 services-wrap d-flex">
								<div class="icon d-flex justify-content-center align-items-center"><span class="flaticon-file"></span></div>
								<div class="media-body pl-4">
									<h3>We Are Responsive</h3>
									<p>You can easily access our platform on both mobile and desktop</p>
								</div>
							</div>      
						</div>
						<div class="col-md-12 d-flex align-self-stretch ftco-animate">
							<div class="media block-6 services-wrap d-flex">
								<div class="icon d-flex justify-content-center align-items-center"><span class="flaticon-locked"></span></div>
								<div class="media-body pl-4">
									<h3>We Are Detailed</h3>
									<p>Prospective tenants get all the details and the location of the house before leasing the house</p>
								</div>
							</div>      
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

home/templates/home/sections/testimonies.html
{% load static %}

<section class="ftco-section testimony-section bg-light">
	<div class="container">
		<div class="row justify-content-center mb-5">
			<div class="col-md-7 text-center heading-section ftco-animate">
				<span class="subheading">Testimonial</span>
				<h2 class="mb-3">Our Clients</h2>
			</div>
		</div>
		<div class="row ftco-animate">
			<div class="col-md-12">
				<div class="carousel-testimony owl-carousel ftco-owl">
					<div class="item">
						<div class="testimony-wrap py-4">
							<div class="text">
								<p class="mb-4">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
								tempor incididunt ut labore et dolore magna aliqua.</p>
								<div class="d-flex align-items-center">
									<div class="user-img" style="background-image: url('{% static 'home/images/hirani.jpg' %}')"></div>
									<div class="pl-3">
										<p class="name">Hirani Laxit</p>
										<span class="position">Tenant</span>
									</div>
								</div>
							</div>
						</div>
					</div>
					<div class="item">
						<div class="testimony-wrap py-4">
							<div class="text">
								<p class="mb-4">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
								tempor incididunt ut labore et dolore magna aliqua.</p>
								<div class="d-flex align-items-center">
									<div class="user-img" style="background-image: url('{% static 'home/images/hirani.jpg' %}')"></div>
									<div class="pl-3">
										<p class="name">Laxit Hirani</p>
										<span class="position">Landlord</span>
									</div>
								</div>
							</div>
						</div>
					</div>
					<div class="item">
						<div class="testimony-wrap py-4">
							<div class="text">
								<p class="mb-4">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
								tempor incididunt ut labore et dolore magna aliqua.</p>
								<div class="d-flex align-items-center">
									<div class="user-img" style="background-image: url({% static 'home/images/hirani.jpg' %})"></div>
									<div class="pl-3">
										<p class="name">Hirani Laxit</p>
										<span class="position">Tenant</span>
									</div>
								</div>
							</div>
						</div>
					</div>
					<div class="item">
						<div class="testimony-wrap py-4">
							<div class="text">
								<p class="mb-4">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
								tempor incididunt ut labore et dolore magna aliqua.</p>
								<div class="d-flex align-items-center">
									<div class="user-img" style="background-image: url('{% static 'home/images/hirani.jpg' %}')"></div>
									<div class="pl-3">
										<p class="name">Laxit Hirani</p>
										<span class="position">Landord</span>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>