home/urls.py
from django.urls import re_path
from .import views

app_name = 'home'

urlpatterns = [
	re_path(r'^$', views.home, name='home')
]

properties/urls.py
from django.urls import re_path
from .import views

app_name = 'properties'

urlpatterns = [
	re_path(r'^$', views.properties, name='properties-list'),
	re_path(r'^properties-create/$', views.property_create, name='properties-create'),
	re_path(r'^property/(?P<slug>[\w-]+)/$', views.property_detail, name='properties-detail'),
	re_path(r'^appartment-create/$', views.appartment_create, name='appartment-create'),
	re_path(r'^house-create/$', views.house_create, name='house-create'),
	re_path(r'^generate-invoice/(?P<slug>[\w-]+)/$', views.generate_invoice, name='generate-invoice'),
]

properties/models.py
from django.db import models
from django.utils.text import slugify
from accounts.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.urls import reverse

class Property(models.Model):
	slug = models.SlugField(
		unique=True,
		blank=True,
		null=True
	)

	name = models.CharField(
		max_length=50,
		blank=True,
		null=True
	)

	address = models.CharField(
		max_length=50,
		blank=True,
		null=True
	)

	image = models.ImageField(
		upload_to='properties',
		blank=True,
		null=True
	)

	rent = models.IntegerField()
	description = models.TextField()
	bedrooms = models.IntegerField()
	washrooms = models.IntegerField()

	def __str__(self):
		return self.name

	def save(self, *args, **kwargs):
		self.slug = slugify(self.name)
		super().save(*args, **kwargs)

class Appartment(models.Model):
	slug = models.SlugField(
		unique=True,
		blank=True,
		null=True
	)

	name = models.CharField(
		max_length=50,
		blank=True,
		null=True
	)

	location = models.CharField(
		max_length=50,
		blank=True,
		null=True
	)

	def __str__(self):
		return self.name

	def save(self, *args, **kwargs):
		self.slug = slugify(self.name)
		super().save(*args, **kwargs)


class House(models.Model):
	slug = models.SlugField(
		unique=True,
		blank=True,
		null=True
	)

	name = models.CharField(
		max_length=50,
		blank=True,
		null=True
	)

	address = models.CharField(
		max_length=50,
		blank=True,
		null=True
	)

	vacant = models.BooleanField(default=True)

	appartment = models.ForeignKey(
		Appartment,
		blank=True,
		null=True,
		on_delete=models.CASCADE
	)

	tenant = models.ForeignKey(
		User,
		blank=True,
		null=True,
		on_delete=models.CASCADE
	)

	rent = models.IntegerField()
	description = models.TextField()
	bedrooms = models.IntegerField()
	washrooms = models.IntegerField()

	@property
	def is_vacant(self):
		return self.vacant

	def __str__(self):
		return self.name

	def get_absolute_url(self):
		return reverse('properties:properties-detail', args=[str(self.slug)])

	def save(self, *args, **kwargs):
		self.slug = slugify(self.name)
		super().save(*args, **kwargs)

class OccupiedHouse(models.Model):
	house = models.OneToOneField(
		House,
		on_delete=models.CASCADE,
		null=True,
		related_name='occupied_house'
	)

	rent_status = models.CharField(
		max_length=15,
		blank=True,
		null=True,
		default='PENDING'
	)

	def __str__(self):
		return self.house.name

@receiver(post_save, sender=House)
def house_postsave(sender, instance, created, *args, **kwargs):
	if instance.is_vacant == False:
		OccupiedHouse.objects.get_or_create(house=instance)

properties/forms.py
from django import forms
from .models import Property, Appartment, House, OccupiedHouse

class PropertyCreateForm(forms.ModelForm):
	class Meta:
		model = Property
		fields = ['name', 'address', 'image', 'rent', 'description', 'bedrooms', 'washrooms']

	name = forms.CharField(
		required = True,
		label = 'Property Name',
		widget = forms.TextInput(
			attrs = {
				'class': 'form-control',
			}),
	)

	address = forms.CharField(
		required = True,
		label = 'Address',
		widget = forms.TextInput(
			attrs = {
				'class': 'form-control',
			}),
	)

	image = forms.ImageField(
		required = False,
		widget = forms.FileInput(
			attrs = {
				'class': 'form-control',
			}),
	)

	rent = forms.IntegerField(
		required = True,
		label = 'Rent',
		widget = forms.NumberInput(
			attrs = {
				'class': 'form-control',
			}),
	)

	description = forms.CharField(
		required = True,
		label = 'Description',
		widget = forms.Textarea(
			attrs = {
				'class': 'form-control mb-3',
				'rows': 5,
		}),
	)

	bedrooms = forms.IntegerField(
		required = True,
		label = 'Bedrooms',
		widget = forms.NumberInput(
			attrs = {
				'class': 'form-control',
			}),
	)

	washrooms = forms.IntegerField(
		required = True,
		label = 'Washrooms',
		widget = forms.NumberInput(
			attrs = {
				'class': 'form-control',
			}),
	)

class AppartmentCreateForm(forms.ModelForm):
	class Meta:
		model = Appartment
		fields = ['name', 'location']

	def __init__(self, *args, **kwargs):
		super(AppartmentCreateForm, self).__init__(*args, **kwargs)
		for fieldname, field in self.fields.items():
			field.widget.attrs.update({
				'class': 'form-control',
				'placeholder': '',
			})

class HouseCreateForm(forms.ModelForm):
	class Meta:
		model = House
		fields = '__all__'
		exclude = ['slug']

	def __init__(self, *args, **kwargs):
		super(HouseCreateForm, self).__init__(*args, **kwargs)
		for fieldname, field in self.fields.items():
			field.widget.attrs.update({
				'class': 'form-control',
				'placeholder': '',
			})

properties/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.core.mail import EmailMultiAlternatives
from django.template.loader import render_to_string
from django.contrib import messages
from django.db.models import Q
from .models import Property, House
from .forms import PropertyCreateForm, AppartmentCreateForm, HouseCreateForm

def properties(request):
	template_name = 'properties/properties.html'
	properties = Property.objects.all()

	query = request.GET.get("q", None)

	if query is not None:
		properties = Property.objects.filter(
			Q(name__icontains=query) |
			Q(address__icontains=query) |
			Q(description__icontains=query)
		)

	context = {
		'properties': properties,
	}

	return render(request, template_name, context)

def property_create(request):
	template_name = 'properties/property_create.html'
	if request.method == 'POST':
		form = PropertyCreateForm(request.POST or None)
		if form.is_valid():
			form.save()
			messages.success(request, ('Your property has been created!'))
			return redirect('properties:properties-list')
	else:
		form = PropertyCreateForm(label_suffix='')

	context = {
		'form': form,
	}

	return render(request, template_name, context)

def appartment_create(request):
	template_name = 'properties/appartment_create.html'

	if request.method == 'POST':
		form = AppartmentCreateForm(request.POST or None)
		if form.is_valid():
			form.save()
			messages.success(request, ('Your appartment has been created!'))
			return redirect('dashboard:dashboard')
	else:
		form = AppartmentCreateForm(label_suffix='')

	context = {
		'form': form,
	}

	return render(request, template_name, context)

def house_create(request):
	template_name = 'properties/house_create.html'

	if request.method == 'POST':
		form = HouseCreateForm(request.POST or None)
		if form.is_valid():
			form.save()
			messages.success(request, ('A new house has been created!'))
			return redirect('dashboard:dashboard')
	else:
		form = HouseCreateForm(label_suffix='')

	context = {
		'form': form,
	}

	return render(request, template_name, context)

def property_detail(request, slug):
	template_name = 'properties/property.html'
	house = get_object_or_404(House, slug=slug)

	context = {
		'house': house,
	}

	return render(request, template_name, context)

def generate_invoice(request, slug):
	house = get_object_or_404(House, slug=slug)

	from_email = 'lhirani9@gmail.com'
	to = request.user.email

	subject = 'House Report'
	text_content = 'House Report'

	html_content = render_to_string('email/invoice.html', {
		'username': request.user.username,
		'house': house,
		}
	)

	if html_content:
		msg = EmailMultiAlternatives(subject, text_content, from_email, [to])
		msg.attach_alternative(html_content, "text/html")
		msg.content_subtype = "html"
		msg.send()
		messages.success(request, 'Your invoice has been successfully generated. Kindly check your email')

		return redirect('dashboard:dashboard')

properties/templates/properties/appartment_create.html
{% extends 'base/base.html' %}

{% load static %}

{% block content %}

<div id="dashboard">
	{% include 'dashboard/includes/sidebar.html' %}

	<div class="main-container">
		{% include 'dashboard/navbar.html' %}
		<section class="dashboard">
			<div class="container">
				<div class="card">
					<div class="card-header font-weight-bold ">
						Create Appartment
					</div>

					<div class="card-body">
						<div class="row">
							<div class="col-md-6">
								<form method="POST" action="">

									{% csrf_token %}
									{% if form.errors %}
										{% for error in form.non_field_errors %}
										<div class="alert alert-danger alert-dismissable fade show" role="alert">
											{{ error|escape }}
											<button type="button" class="close" data-dismiss="alert" aria-label="Close" aria-hidden="true">&times;</button>
										</div>
										{% endfor %}

										{% for field in form %}
											{% for error in field.errors %}
											<div class="alert alert-danger alert-dismissable fade show" role="alert">
												{{ error|escape }}
												<button type="button" class="close" data-dismiss="alert" aria-label="Close" aria-hidden="true">&times;</button>
											</div>
											{% endfor %}
										{% endfor %}

									{% endif %}
									
									{{ form.as_p }}

									<button type="submit" class="form-control btn btn-primary mt-3">Create Appartment</button>

								</form>
							</div>
						</div>
					</div>
				</div>

			</div>
		</section>
	</div>
</div>
{% endblock content %}

properties/templates/properties/house_create.html
{% extends 'base/base.html' %}

{% load static %}

{% block content %}

<div id="dashboard">
	{% include 'dashboard/includes/sidebar.html' %}

	<div class="main-container">
		{% include 'dashboard/navbar.html' %}
		<section class="dashboard">
			<div class="container">
				<div class="card">
					<div class="card-header font-weight-bold ">
						Create House
					</div>

					<div class="card-body">
						<div class="row">
							<div class="col-md-6">
								<form method="POST" action="">

									{% csrf_token %}
									{% if form.errors %}
										{% for error in form.non_field_errors %}
										<div class="alert alert-danger alert-dismissable fade show" role="alert">
											{{ error|escape }}
											<button type="button" class="close" data-dismiss="alert" aria-label="Close" aria-hidden="true">&times;</button>
										</div>
										{% endfor %}

										{% for field in form %}
											{% for error in field.errors %}
											<div class="alert alert-danger alert-dismissable fade show" role="alert">
												{{ error|escape }}
												<button type="button" class="close" data-dismiss="alert" aria-label="Close" aria-hidden="true">&times;</button>
											</div>
											{% endfor %}
										{% endfor %}

									{% endif %}
									
									{{ form.as_p }}

									<button type="submit" class="form-control btn btn-primary mt-3">Create House</button>

								</form>
							</div>
						</div>
					</div>
				</div>

			</div>
		</section>
	</div>
</div>
{% endblock content %}

properties/templates/properties/properties.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}
{% include 'home/sections/navbar.html' %}

<style type="text/css">
	.hero-wrap.hero-wrap-2, .overlay, .overlay-2{
		height: 400px !important;
	}
</style>

<section class="hero-wrap hero-wrap-2 ftco-degree-bg js-fullheight" style="background-image: url('{% static 'home/images/couch.jpg' %}');" >
	<div class="overlay"></div>
	<div class="overlay-2"></div>
</section>

<section class="ftco-section goto-here pt-0" id="properties">
	<div class="container">
		<div class="row justify-content-center">
			<div class="col-md-12 heading-section text-center mb-5">
				<span class="subheading">What we offer</span>
				<h2 class="mb-2">Some Of Our Properties</h2>
			</div>
		</div>

		<div class="row justify-content-center">
			<div class="col-md-6 heading-section text-center mb-5">
				<form class="search" method="GET" action="{% url 'properties:properties-list' %}">
					<div class="input-group">
						<input type="text" name="q" class="form-control" placeholder="Search for a property..." aria-label="Search for a property">

						<div class="input-group-append">
							<input type="submit" class="btn search-btn" value="Search">
						</div>
						
					</div>
				</form>
			</div>
		</div>

		<div class="row">
			{% for property in properties %}
				<div class="col-md-4">
					<div class="property-wrap">
						<div class="img d-flex align-items-center justify-content-center" style="background-image: url(' {% if property.image %} {{ property.image.url }} {% else %} {% static 'home/images/work-1.jpg' %} {% endif %}');"> 
							<a href="#"></a>
							<div class="list-agent d-flex align-items-center">
								<a href="#" class="agent-info d-flex align-items-center">
									<h3 class="mb-0 ml-2">{{ property.name }}</h3>
								</a>
								<div class="tooltip-wrap d-flex"> 
									<a href="#" class="icon-2 d-flex align-items-center justify-content-center" data-toggle="tooltip" data-placement="top" title="Like">
										<span class="ion-ios-heart"><i class="sr-only">Like</i></span>
									</a>
									<a href="#" class="icon-2 d-flex align-items-center justify-content-center" data-toggle="tooltip" data-placement="top" title="View">
										<span class="ion-ios-eye"><i class="sr-only">View</i></span>
									</a>
								</div>
							</div>
						</div>
						<div class="text">
							<p class="price mb-3"><span class="orig-price">{{ property.rent }}<small>/month</small></span></p>
							<h3 class="mb-0"><a href="#">{{property.name}}</a></h3>
							<span class="location d-inline-block mb-3"><i class="ion-ios-pin mr-2"></i>{{ property.address }}</span>
							<ul class="property_list">
								<li><span class="flaticon-bed"></span>{{ property.bedrooms }}</li>
								<li><span class="flaticon-bathtub"></span>{{ property.washrooms }}</li>
							</ul>
						</div>
					</div>
				</div>
			{% empty %}
				{% if request.GET.q %}
					<p class="text-center w-100">No properties found</p>
				{% else %}
					<p class="text-center w-100">Properties don't exist yet!</p>
				{% endif %}
			{% endfor %}

		</div>
	</div>
</section>

{% endblock content %}

properties/templates/properties/property.html
{% extends 'base/base.html' %}

{% load static %}

{% block content %}

<style type="text/css">
	h6 {
		font-weight: 700 !important;
	}
</style>

<div id="dashboard">
	{% include 'dashboard/includes/sidebar.html' %}

	<div class="main-container">
		{% include 'dashboard/navbar.html' %}
		<section class="dashboard">
			<div class="container">
				<div class="card">
					<div class="card-header font-weight-bold ">
						{{ house.name }}
						<a href="{% url 'properties:generate-invoice' house.slug %}" class="btn btn-primary mb-3 float-right">Generate Invoice</a>
					</div>

					<hr>

					<div class="card-body">
						<div class="row">
							<div class="col-md-6">
								<h6>Property Name</h6>
								<p>{{ house.name }}</p>

								<h6>Address</h6>
								<p>{{ house.address }}</p>

								<h6>Vacant</h6>
								<p>{{ house.vacant }}</p>

								<h6>Appartment</h6>
								<p>{{ house.appartment }}</p>

								<h6>Tenant</h6>
								<p>{{ house.tenant }}</p>

							</div>
							<div class="col-md-6">
								<h6>Description</h6>
								<p>{{ house.description }}</p>

								<h6>Rent</h6>
								<p>{{ house.rent }}</p>

								<h6>Bedrooms</h6>
								<p>{{ house.bedrooms }}</p>

								<h6>Washrooms</h6>
								<p>{{ house.washrooms }}</p>
							</div>
						</div>

					</div>
				</div>

			</div>
		</section>
	</div>
</div>
{% endblock content %}

properties/templates/properties/property_create.html
{% extends 'base/base.html' %}

{% load static %}

{% block content %}

<div id="dashboard">
	{% include 'dashboard/includes/sidebar.html' %}

	<div class="main-container">
		{% include 'dashboard/navbar.html' %}
		<section class="dashboard">
			<div class="container">
				<div class="card">
					<div class="card-header font-weight-bold ">
						Create Property
					</div>

					<div class="card-body">
						<div class="row">
							<div class="col-md-6">
								<form method="POST" action="">

									{% csrf_token %}
									{% if form.errors %}
										{% for error in form.non_field_errors %}
										<div class="alert alert-danger alert-dismissable fade show" role="alert">
											{{ error|escape }}
											<button type="button" class="close" data-dismiss="alert" aria-label="Close" aria-hidden="true">&times;</button>
										</div>
										{% endfor %}

										{% for field in form %}
											{% for error in field.errors %}
											<div class="alert alert-danger alert-dismissable fade show" role="alert">
												{{ error|escape }}
												<button type="button" class="close" data-dismiss="alert" aria-label="Close" aria-hidden="true">&times;</button>
											</div>
											{% endfor %}
										{% endfor %}

									{% endif %}
									
									{{ form.as_p }}

									<button type="submit" class="form-control btn btn-primary mt-3">Create Property</button>

								</form>
							</div>
						</div>
					</div>
				</div>

			</div>
		</section>
	</div>
</div>
{% endblock content %}