accounts/urls.py
from django.urls import re_path

from .import views

app_name = 'accounts'

urlpatterns = [
	re_path(r'^tenant-create/$', views.tenant_create, name='tenant-create'),
]

dashboard/urls.py
from django.urls import re_path
from .import views

app_name = 'dashboard'

urlpatterns = [
	re_path(r'^$', views.dashboard, name='dashboard'),
	re_path(r'^tenants/$', views.tenants, name='tenant-list'),
	re_path(r'^send-report/$', views.house_report, name='house-report'),
]

home/urls.py
from django.urls import re_path
from .import views

app_name = 'home'

urlpatterns = [
	re_path(r'^$', views.home, name='home')
]

properties/urls.py
from django.urls import re_path
from .import views

app_name = 'properties'

urlpatterns = [
	re_path(r'^$', views.properties, name='properties-list'),
	re_path(r'^properties-create/$', views.property_create, name='properties-create'),
	re_path(r'^property/(?P<slug>[\w-]+)/$', views.property_detail, name='properties-detail'),
	re_path(r'^appartment-create/$', views.appartment_create, name='appartment-create'),
	re_path(r'^house-create/$', views.house_create, name='house-create'),
	re_path(r'^generate-invoice/(?P<slug>[\w-]+)/$', views.generate_invoice, name='generate-invoice'),
]

dashboard/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from accounts.models import User
from properties.models import House, Appartment
from django.core.mail import EmailMultiAlternatives
from django.template.loader import render_to_string
from django.contrib import messages

@login_required
def dashboard(request):
	template_name = 'dashboard/dashboard.html'
	occupied_houses = House.objects.filter(vacant=False)
	vacant_houses = House.objects.filter(vacant=True)
	appartments = Appartment.objects.all()

	context = {
		'occupied_houses': occupied_houses,
		'appartments': appartments,
		'vacant_houses': vacant_houses,
	}

	return render(request, template_name, context)

def tenants(request):
	template_name = 'dashboard/tenants.html'
	tenants = User.objects.all().filter(landlord=False).exclude(username=request.user)
	context = {
		'tenants': tenants,
	}
	return render(request, template_name, context)

def house_report(request):
	occupied_houses = House.objects.filter(vacant=False)
	vacant_houses = House.objects.filter(vacant=True)
	appartments = Appartment.objects.all()

	from_email = 'lhirani9@gmail.com'
	to = request.user.email

	subject = 'House Report'
	text_content = 'House Report'

	html_content = render_to_string('email/house_report.html', {
		'username': request.user.username,
		'occupied_houses': occupied_houses,
		'appartments': appartments,
		'vacant_houses': vacant_houses,
		}
	)

	if html_content:
		msg = EmailMultiAlternatives(subject, text_content, from_email, [to])
		msg.attach_alternative(html_content, "text/html")
		msg.content_subtype = "html"
		msg.send()
		messages.success(request, 'Your report has been successfully generated. Kindly check your email')

		return redirect('dashboard:dashboard')

dashboard/templates/dashboard/dashboard.html
{% extends 'base/base.html' %}

{% load static %}

{% block content %}
<style type="text/css">
	table a {
		color: #963e00;
		font-weight: 700;
	}
</style>
	
	<div id="dashboard">
	{% include 'dashboard/includes/sidebar.html' %}

	<div class="main-container">
		{% include 'dashboard/navbar.html' %}
		<section class="dashboard">
			<div class="container">
				<div class="card">
					<div class="card-header font-weight-bold ">
						Apartments
					</div>

					<div class="card-body">
						<a href="{% url 'dashboard:house-report' %}" class="btn btn-primary mb-3 float-right">Generate Report</a>
						<a href="{% url 'properties:appartment-create' %}" class="btn btn-primary mb-3 mr-3 float-right">Add Appartment</a>

						<table class="table table-hover table-borderless">
							<thead>
								<tr>
									<th scope="col">ID</th>
									<th scope="col">Name</th>
									<th scope="col">Location</th>
								</tr>
							</thead>
							<tbody>
								{% for appartment in appartments %}
									<tr>
										<th scope="row">{{ appartment.id }}</th>
										<td>{{ appartment.name }}</td>
										<td>{{ appartment.location }}</td>
									</tr>
								{% endfor %}
							</tbody>
						</table>
					</div>
				</div>
				<div class="card">
					<div class="card-header font-weight-bold ">
						Occupied Houses
					</div>

					<div class="card-body">

						<a href="{% url 'properties:house-create' %}" class="btn btn-primary mb-3 float-right ">Add House</a>

						<table class="table table-hover table-borderless">
							<thead>
								<tr>
									<th scope="col"></th>
									<th scope="col">Apartment</th>
									<th scope="col">House No.</th>
									<th scope="col">Tenant</th>
									<th scope="col">Payment Status</th>
								</tr>
							</thead>
							<tbody>
								
								{% for house in occupied_houses %}
									<a href="#">
										<tr>
											<th scope="row">{{ house.id }}</th>
											<td>
												{{ house.appartment.name }}
											</td>
											<td>{{ house.name }}</td>
											<td>{{ house.tenant }}</td>
											<td class="status">{{ house.occupied_house.rent_status }}</td>
										</tr>
									</a>
								{% endfor %}
							</tbody>
						</table>
					</div>
				</div>

				<div class="card">
					<div class="card-header font-weight-bold ">
						Vacant Houses
					</div>

					<div class="card-body">
						<a href="{% url 'properties:house-create' %}" class="btn btn-primary mb-3 float-right ">Add House</a>
						
						<table class="table table-hover table-borderless">
							<thead>
								<tr>
									<th scope="col">House No.</th>
									<th scope="col">House Name.</th>
									<th scope="col">Apartment</th>
									<th scope="col">Location</th>
								</tr>
							</thead>

							<tbody>
								{% for house in vacant_houses %}
									<tr>
										<th scope="row">{{ house.id }}</th>
										<td>
											<a href="{{ house.get_absolute_url }}">
												{{ house.name }}
											</a>
										</td>
										<td>{{ house.appartment.name }}</td>
										<td>{{ house.appartment.location }}</td>
									</tr>
								{% endfor %}
							</tbody>
						</table>
					</div>
				</div>
			</div>
		</section>
	</div>
	</div>
{% endblock content %}

dashboard/templates/dashboard/navbar.html
<nav class="navbar navbar-expand-lg navbar-light py-3" id="mainNav">
	<div class="container">
		<a class="navbar-brand js-scroll-trigger" href="{% url 'dashboard:dashboard' %}">
			Alquiler-Admin
		</a>
		<button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>

		<div class="collapse navbar-collapse" id="navbarResponsive">
			<ul class="navbar-nav ml-auto pl-2 my-2 my-lg-0">
				<li class="nav-item">
					<a class="nav-link js-scroll-trigger" href="{% url 'account_logout' %}" title="Sign out"><i class="fas fa-sign-out-alt"></i></a>
				</li>
			</ul>
		</div>

	</div>
</nav>

dashboard/templates/dashboard/tenants.html
{% extends 'base/base.html' %}

{% load static %}

{% block content %}
	
	<div id="dashboard">
	{% include 'dashboard/includes/sidebar.html' %}

	<div class="main-container">
		{% include 'dashboard/navbar.html' %}
		<section class="dashboard">
			<div class="container">
				<div class="card">
					<div class="card-header font-weight-bold ">
						Tenants
					</div>

					<div class="card-body">
						<a href="{% url 'accounts:tenant-create' %}" class="btn btn-primary mb-3 float-right">Add Tenant</a>
						<table class="table table-hover table-borderless">
							<thead>
								<tr>
									<th scope="col"></th>
									<th scope="col">First Name</th>
									<th scope="col">Last Name</th>
									<th scope="col">Phone Number</th>
									<th scope="col">Email Address</th>
									<th scope="col">Occupation</th>
									<th scope="col">KRA</th>
								</tr>
							</thead>
							<tbody>
								{% for tenant in tenants %}
									<tr>
										<td scope="col">{{ tenant.id }}</td>
										<td scope="col">{{ tenant.firstname }}</td>
										<td scope="col">{{ tenant.lastname }}</td>
										<td scope="col">{{ tenant.phone_number }}</td>
										<td scope="col">{{ tenant.email }}</td>
										<td scope="col">{{ tenant.occupation }}</td>
										<td scope="col">{{ tenant.kra }}</td>
									</tr>
								{% endfor %}
							</tbody>
						</table>
					</div>
				</div>
			</div>
		</section>
	</div>
	</div>
{% endblock content %}